import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';

@Component({
  selector: 'dapp-ui-layout',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterOutlet],
  template: `
    <div class="h-full flex flex-col">
      <div
        class="navbar bg-base-300 text-neutral-content flex-col md:flex-row space-y-2 md:space-y-0"
      >
        <div class="flex-1">
          <a class="btn btn-ghost normal-case text-xl" routerLink="/">
            <img
              class="h-4 md:h-6"
              alt="Solana Logo"
              src="/assets/solana-logo.png"
            />
          </a>
          @for (link of links; track link) {
          <a
            class="menu menu-horizontal px-1 space-x-2"
            [routerLink]="link.path"
            >{{ link.label }}</a
          >
          }
        </div>
        <div class="flex-none space-x-2">
          <button>wallet</button>
          <button>Devnet</button>
        </div>
      </div>
      <!--      <ClusterChecker>-->
      <!--        <AccountChecker />-->
      <!--      </ClusterChecker>-->

      <main>
        <router-outlet />
      </main>

      <div class="flex-grow mx-4 lg:mx-auto">
        <div class="text-center my-32">
          <!--              <span className="loading loading-spinner loading-lg"></span>-->
        </div>

        <!--        <Toaster position="bottom-right" />-->
      </div>

      <footer class="footer footer-center p-4 bg-base-300 text-base-content">
        <aside>
          <p>
            Generated by
            <a
              class="link hover:text-white"
              href="https://github.com/solana-developers/create-solana-dapp"
              target="_blank"
              rel="noopener noreferrer"
            >
              create-solana-dapp
            </a>
          </p>
        </aside>
      </footer>
    </div>
  `,
  styles: ``,
})
export class UiLayoutComponent {
  @Input() links!: { label: string; path: string }[];
}

@Component({
  selector: 'dapp-app-hero',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="hero py-[64px]">
      <div class="hero-content text-center">
        <div class="max-w-2xl">
          @if (title) {
          <h1 class="text-5xl font-bold">{{ title }}</h1>
          } @if (subtitle) {
          <p class="py-6">{{ subtitle }}</p>
          }
          <ng-content />
        </div>
      </div>
    </div>
  `,
  styles: ``,
})
export class AppHeroComponent {
  @Input() title?: string;
  @Input() subtitle?: string;
}

@Component({
  selector: 'dapp-app-table',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="overflow-x-auto">
      <table class="table border-4 border-separate border-base-300">
        <thead>
          <tr>
            <th>Name / Network / Endpoint</th>
            <th class="text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr class="bg-base-200">
            <td class="space-y-2">
              <div class="whitespace-nowrap space-x-2">
                <span class="text-xl">
                  <button class="link link-secondary">devnet</button>
                </span>
              </div>
              <span class="text-xs">Network: </span>
              <div class="whitespace-nowrap text-gray-500 text-xs">
                http://localhost:8899
              </div>
            </td>
            <td class="space-x-2 whitespace-nowrap text-center">
              <button class="btn btn-xs btn-default btn-outline">
                <i class="fas fa-trash" size="16"></i>
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  `,
  styles: `
`,
})
export class AppTableComponent {
  @Input() name?: string;
  @Input() endpoint?: string;
}
